services:
  frontend:
    build:
      context: ./frontend
    container_name: vishwakamal-web
    env_file:
      - ./frontend/.env.local
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
